### GET request to example server
GET http://localhost:8080/api/estudiantes

###


POST http://localhost:8080/api/estudiantes
Content-Type: application/json

{
    "nombreCompleto": "Juan Perez",
    "correo": "aaaaa@aaa.com",
    "password": "123",
    "programa": "ING_SISTEMAS"
}