spring.application.name=ProyectoAvanzada
# MariaDB database connection settings
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?serverTimezone=UTC
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#se cambia la contraseña por la que se tiene en la BD y el puerto en caso de ser el 3306 por defecto

# Hibernate/JPA settings (optional, but useful)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=${OPEN_ROUTER}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=openai/gpt-4o-mini