spring.application.name=ProyectoAvanzada
# MariaDB database connection settings
spring.datasource.url=jdbc:mariadb://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
#se cambia la contraseña por la que se tiene en la BD y el puerto en caso de ser el 3306 por defecto
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate/JPA settings (optional, but useful)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPEN_ROUTER}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=openai/gpt-4o-mini